### PR TITLE
Module 1: Hello Microverse

### PR DESCRIPTION
**Pull request by boniface193**
### Hello Microverse

[Old PR Link
](https://github.com/boniface193/hello_microverse/pull/1)

Linter
 - .hintrc file was added
 - .stylelintrc.json file was added
html
 - html file is included
css
 - css file was included
package-lock.json
 - package-lock.json file was generated

### CODE REVIEW

**Review by Yerimah — CHANGES_REQUESTED** [review]
# Status: Invalid Pull Request 🔴 

Hi @boniface193 👋,
 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
for invalid pul request

## Invalid Code Review Request

You have submitted a project for re-review without the history of your previous review. I would suggest you submit a re-review request using the same PR link, or provide the old PR link in the PR description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by boniface193** [comment]
@Yerimah thank you for your update, i have included the old PR link on the discription

**Review by joskalenda — APPROVED** [review]
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @boniface193 , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
|  |

### Highlights
✅ Good commit messages
✅ correct Git flow
✅ Descriptive pull request

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by boniface193** [comment]
wow, i am happy.

**Pull request merged**
